source 'https://github.com/CocoaPods/Specs.git'

target 'AXSideButtonTabBarController', :exclusive => true do
  pod 'AXSideButtonTabBarController', :path => '../'
  pod 'FontAwesomeKit', '~> 2.2'
end

target 'Tests', :exclusive => true do
  pod 'AXSideButtonTabBarController', :path => '../'
end
